/aruco_node:
  ros__parameters:
    marker_size: 0.8
    aruco_dictionary_id: DICT_4X4_100
    image_topic: /camera
    camera_info_topic: /camera_info
    camera_frame: x500_mono_cam_0/mono_cam/base_link/imager